#!/usr/bin/env python3
"""Build minimal homebrew artifacts that do not require proprietary blobs."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


TOKEN_FOR = 0x81
TOKEN_NEXT = 0x82
TOKEN_GOTO = 0x89
TOKEN_PRINT = 0x99
TOKEN_POKE = 0x97
TOKEN_TO = 0xA4
TOKEN_REM = 0x8F
TOKEN_STEP = 0xA9
TOKEN_AND = 0xAF


def ascii_bytes(text: str) -> bytes:
  return text.upper().encode("ascii", "replace")


def basic_line(line_number: int, payload: bytes) -> bytes:
  return line_number.to_bytes(2, "little") + payload + b"\x00"


def build_c64_prg() -> bytes:
  lines = [
    basic_line(10, bytes([TOKEN_PRINT]) + b' "' + bytes([147, 5]) + ascii_bytes("CHIPVIZ C64 HOMEBREW") + b'"'),
    basic_line(20, bytes([TOKEN_PRINT]) + b' "' + ascii_bytes("RASTER PETSCII DEMO SEED") + b'"'),
    basic_line(30, bytes([TOKEN_PRINT]) + b' "' + ascii_bytes("COLOR BARS + VIC BORDER PULSE") + b'"'),
    basic_line(35, bytes([TOKEN_REM]) + b" " + ascii_bytes("CHIPVIZ HOME BREW STYLE")),
    basic_line(
      40,
      bytes([TOKEN_FOR])
      + b" I=0 "
      + bytes([TOKEN_TO])
      + b" 15:"
      + bytes([TOKEN_POKE])
      + b" 53280,I:"
      + bytes([TOKEN_POKE])
      + b" 53281,15-I:"
      + bytes([TOKEN_NEXT]),
    ),
    basic_line(
      45,
      bytes([TOKEN_FOR])
      + b" P=1024 "
      + bytes([TOKEN_TO])
      + b" 1063:"
      + bytes([TOKEN_POKE])
      + b" P,81:"
      + bytes([TOKEN_NEXT]),
    ),
    basic_line(
     50,
     bytes([TOKEN_FOR])
     + b" C=55296 "
     + bytes([TOKEN_TO])
     + b" 55335:"
     + bytes([TOKEN_POKE])
     + b" C,(C-55296) "
     + bytes([TOKEN_AND])
     + b" 15:"
     + bytes([TOKEN_NEXT]),
    ),
    basic_line(
     55,
     bytes([TOKEN_FOR])
     + b" W=0 "
     + bytes([TOKEN_TO])
     + b" 7:"
     + bytes([TOKEN_FOR])
     + b" X=0 "
     + bytes([TOKEN_TO])
     + b" 7:"
     + bytes([TOKEN_POKE])
     + b" 1024+W*40+X,160+W:"
     + bytes([TOKEN_POKE])
     + b" 55296+W*40+X,1+W:"
     + bytes([TOKEN_NEXT])
     + b" X:"
     + bytes([TOKEN_NEXT])
     + b" W",
    ),
    basic_line(60, bytes([TOKEN_GOTO]) + b" 40"),
  ]
  program = bytearray()
  load_address = 0x0801
  next_address = load_address
  for line in lines:
    next_address += 2 + len(line)
    program += next_address.to_bytes(2, "little")
    program += line
  program += b"\x00\x00"
  return load_address.to_bytes(2, "little") + bytes(program)


def build_snes_sfc() -> bytes:
  rom = bytearray([0x00] * 0x8000)
  code = bytes(
    [
      0x78,  # sei
      0x18,  # clc
      0xFB,  # xce
      0xC2, 0x30,  # rep #$30
      0xA2, 0xFF, 0x1F,  # ldx #$1fff
      0x9A,  # txs
      0xE2, 0x20,  # sep #$20
      0xA9, 0x00,  # lda #$00
      0x8D, 0x00, 0x21,  # sta $2100 (screen off)
      0x8D, 0x00, 0x00,  # sta $0000 (frame counter)
      0x8D, 0x01, 0x00,  # sta $0001
      0xA9, 0x0F,  # lda #$0f
      0x8D, 0x00, 0x21,  # sta $2100 (full brightness)
      0xAD, 0x12, 0x42,  # lda $4212
      0x30, 0xFB,  # bmi (wait until vblank clears)
      0xAD, 0x12, 0x42,  # lda $4212
      0x10, 0xFB,  # bpl (wait for vblank)
      0xEE, 0x00, 0x00,  # inc $0000
      0xA9, 0x00,  # lda #$00
      0x8D, 0x21, 0x21,  # sta $2121 (CGRAM color 0)
      0xAD, 0x00, 0x00,  # lda $0000
      0x29, 0x1F,  # and #$1f
      0x8D, 0x02, 0x00,  # sta $0002
      0xAD, 0x00, 0x00,  # lda $0000
      0x0A,  # asl
      0x0A,  # asl
      0x29, 0xE0,  # and #$e0
      0x0D, 0x02, 0x00,  # ora $0002
      0x8D, 0x22, 0x21,  # sta $2122
      0xAD, 0x00, 0x00,  # lda $0000
      0x4A,  # lsr
      0x4A,  # lsr
      0x29, 0x7C,  # and #$7c
      0x8D, 0x22, 0x21,  # sta $2122
      0x80, 0xCD,  # bra main loop
    ]
  )
  rom[0:len(code)] = code
  title = b"CHIPVIZ HOMEBREW".ljust(21, b" ")
  header = 0x7FC0
  rom[header:header + 21] = title
  rom[0x7FD5] = 0x20  # LoROM, slow
  rom[0x7FD6] = 0x00  # ROM only
  rom[0x7FD7] = 0x05  # 32 KiB ROM size code
  rom[0x7FD8] = 0x00  # no SRAM
  rom[0x7FD9] = 0x01  # USA
  rom[0x7FDA] = 0x33  # developer/homebrew marker
  rom[0x7FDB] = 0x00
  # Native and emulation reset vectors point to $8000.
  for offset in (0x7FFC, 0x7FFE):
    rom[offset:offset + 2] = (0x8000).to_bytes(2, "little")
  checksum = sum(rom) & 0xFFFF
  complement = checksum ^ 0xFFFF
  rom[0x7FDC:0x7FDE] = complement.to_bytes(2, "little")
  rom[0x7FDE:0x7FE0] = checksum.to_bytes(2, "little")
  return bytes(rom)


def build_status() -> dict:
  return {
    "generated": {
      "c64Fallback": {
        "artifact": "chipviz-c64.prg",
        "status": "tokenized-basic-vic-ii-petscii-fallback",
        "hardwareBootable": True,
      },
      "snesFallback": {
        "artifact": "chipviz-snes.sfc",
        "status": "visible-lorom-cgram-color-cycle-fallback",
        "hardwareBootable": True,
        "validation": "emulator/flashcart/Pocket-core dependent",
      },
    },
    "sdkRequired": {
      "gba": "Hardware-bootable .gba requires a valid GBA header/logo generated by a GBA homebrew SDK; this repo will not embed proprietary boot logo bytes by hand.",
      "n64": "Hardware-bootable .z64 requires libdragon/OpenLibDragon boot/IPL/CIC handling; use the SDK build path rather than a fake ROM blob.",
      "c64": "Complete C64 release artifacts build from cores/c64/homebrew with cc65/cl65; generated BASIC remains a fallback.",
      "snes": "Complete SNES release artifacts build from cores/snes/homebrew with PVSnesLib; generated LoROM remains a fallback.",
    },
  }


def build(output: Path) -> None:
  output.mkdir(parents=True, exist_ok=True)
  (output / "chipviz-c64.prg").write_bytes(build_c64_prg())
  (output / "chipviz-snes.sfc").write_bytes(build_snes_sfc())
  (output / "homebrew-status.json").write_text(
    json.dumps(build_status(), indent=2) + "\n",
    encoding="utf-8",
  )


def build_parser() -> argparse.ArgumentParser:
  parser = argparse.ArgumentParser(description=__doc__)
  parser.add_argument("--output", type=Path, required=True)
  return parser


def main() -> int:
  args = build_parser().parse_args()
  build(args.output)
  return 0


if __name__ == "__main__":
  raise SystemExit(main())
